export const product_requirement_list = [
    {
        id: 'android',
        category: 'platform',
        name: 'Android 客户端',
        title: '是否需要支持 Android 端？',
        desc: 'Android 客户端',
        checked: false,
        dependencies: [],
    },
    {
        id: 'ios',
        category: 'platform',
        name: 'iOS 客户端',
        title: '是否需要支持 iOS 端？',
        desc: 'iOS 客户端',
        checked: false,
        dependencies: [],
    },
    {
        id: 'web',
        category: 'platform',
        name: 'Web端',
        title: '是否需要支持 Web 端？',
        desc: '',
        checked: false,
        dependencies: [1, 3],
    },
    {
        id: 'wx',
        name: '小程序端',
        category: 'platform',
        title: '是否需要支持微信小程序？',
        desc: '',
        checked: false,
        dependencies: [1, 4],
    },
    {
        id: 'windows',
        name: 'Windows 客户端',
        category: 'platform',
        title: '是否需要支持 Windows PC 端？',
        desc: 'Windows 系统软件包，非浏览器',
        checked: false,
        dependencies: [2],
    },
    {
        id: 'macos',
        name: 'macOS 客户端',
        category: 'platform',
        title: '是否需要支持 macOS PC 端？',
        desc: 'macOS 系统软件包，非浏览器',
        checked: false,
        dependencies: [2],
    },
    {
        id: 'linux',
        category: 'platform',
        title: '是否需要支持 Linux PC 端？',
        desc: 'Linux 系统软件包，非浏览器',
        checked: false,
        dependencies: [],
    },
    {
        id: 'linux-x86',
        name: 'Linux(x86/x64) 客户端',
        category: 'platform-linux',
        title: '是否需要支持 CPU 架构为 x86 或 amd64 的 Linux 电脑？',
        desc: '要求 Linux 端所使用的 CPU 架构为 x86 或 amd64',
        checked: false,
        dependencies: [],
    },
    {
        id: 'linux-arm64',
        name: 'Linux(arm64) 客户端',
        category: 'platform-linux',
        title: '是否需要支持 CPU 架构为 arm64 的 Linux 电脑？',
        desc: '要求 Linux 端所使用的 CPU 架构为 arm64',
        checked: false,
        dependencies: [],
    },
    {
        id: 'linux-loongarch',
        name: 'Linux(龙芯) 客户端',
        category: 'platform-linux',
        title: '是否需要支持 CPU 架构为 龙芯的 Linux 电脑？',
        desc: '要求 Linux 端所使用的 CPU 架构为 arm64',
        checked: false,
        dependencies: [],
    },
    {
        id: 'linux-sw',
        name: 'Linux(申威) 客户端',
        category: 'platform-linux',
        title: '是否需要支持 CPU 架构为  申威的 Linux 电脑？',
        desc: '要求 Linux 端所使用的 CPU 架构为 arm64',
        checked: false,
        dependencies: [],
    },
    {
        id: 'moment',
        name: '朋友圈',
        category: 'feature',
        title: '是否需要支持朋友圈功能？',
        desc: '类似微信朋友圈',
        checked: false,
        dependencies: [1],
    },
    {
        id: 'ptt',
        name: '对讲（非发语音消息）',
        category: 'feature',
        title: '是否需要支持对讲功能？',
        desc: '类似对讲机功能，不是发送语音消息',
        checked: false,
        dependencies: [1],
    },
    {
        id: 'conference',
        name: '音视频会议',
        category: 'feature',
        title: '是否需要支持音视频会议？',
        desc: '不是音视频通话，类似微信的音视频通话功能免费使用，这是类似腾讯会议的功能',
        checked: false,
        dependencies: [1, 9],
    },
    {
        id: 'imserver',
        name: '专业版 IM 服务',
        category: 'feature',
        title: 'IM 服务端是否需要支持集群部署？',
        desc: '集群部署、高可用',
        checked: false,
        dependencies: [1],
    },
]

export const commercial_products = [
    {
        id: 1,
        name: '专业版 IM-Server',
        desc: '专业版 IM 服务',
        price: 29000.00,
    },
    {
        id: 2,
        name: 'Windows + macOS PC SDK',
        desc: 'Windows 和 macOS 端的 PC SDK',
        price: 29000.00,
    },
    {
        id: 3,
        name: 'Web SDK',
        desc: '运行在浏览器的 Web 应用使用的 SDK',
        price: 10000.00,
    },
    {
        id: 4,
        name: '小程序 SDK',
        desc: '运行在浏览器的 Web 应用使用的 SDK',
        price: 10000.00,
    },
    {
        id: 5,
        name: 'Linux PC SDK(x86/amd64)',
        desc: 'CPU 架构为 x86/amd64 的 Linux 端使用的 PC SDK',
        price: 29000.00,
    },
    {
        id: 6,
        name: 'Linux PC SDK(arm64)',
        desc: 'CPU 架构为 arm64 的 Linux 端使用的 PC SDK',
        price: 29000.00,
    },
    {
        id: 7,
        name: 'Linux PC SDK(sw)',
        desc: 'CPU 架构为申威的 Linux 端使用的 PC SDK',
        price: 29000.00,
    },
    {
        id: 8,
        name: 'Linux PC SDK(loongarch)',
        desc: 'CPU 架构为龙芯的 Linux 端使用的 PC SDK',
        price: 29000.00,
    },
    {
        id: 9,
        name: '高级版音视频 SDK',
        desc: '实现音视频通话，及音视频会议功能',
        price: 59000.00,
    },

]