export const product_requirement_list = [
    {
        id: 'android',
        category: 'platform',
        name: 'Android 客户端',
        title: '是否需要支持 Android端？',
        desc: '可使用 Android 原生、Flutter 或 uniapp 开发，官方都有相关 demo',
        checked: false,
        dependencies: [],
    },
    {
        id: 'ios',
        category: 'platform',
        name: 'iOS 客户端',
        title: '是否需要支持 iOS？',
        desc: '可使用 iOS 原生、Flutter 或 uniapp 开发，官方都有相关 demo',
        checked: false,
        dependencies: [],
    },
    {
        id: 'harmony',
        category: 'platform',
        name: '鸿蒙客户端',
        title: '是否需要支持鸿蒙？',
        desc: '可使用鸿蒙原生、Flutter 或 uniapp 开发，官方都有相关 demo',
        checked: false,
        dependencies: [11],
    },
    {
        id: 'web',
        category: 'platform',
        name: 'Web端',
        title: '是否需要支持 Web 端？',
        desc: '支持 PC 浏览器、手机浏览器和微信浏览器',
        checked: false,
        dependencies: [1, 3],
    },
    {
        id: 'wx',
        name: '小程序端',
        category: 'platform',
        title: '是否需要支持微信小程序？',
        desc: '支持微信小程序',
        checked: false,
        dependencies: [1, 4],
    },
    {
        id: 'pc',
        name: 'Windows 客户端',
        category: 'platform',
        title: '是否需要支持 PC 端？',
        desc: '包含Windows 和 macOS， 软件包，非浏览器',
        checked: false,
        dependencies: [2],
    },
    {
        id: 'linux',
        category: 'platform',
        title: '是否需要支持 Linux PC 端？',
        desc: '支持 ubuntu、 UOS、麒麟，以及其他国产系统，软件包，非浏览器',
        checked: false,
        archList: [
            {
                name: 'x86/amd64',
                checked: false,
                dependencies: [5],
            },
            {
                name: 'arm64',
                checked: false,
                dependencies: [6],
            },
            {
                name: '申威',
                checked: false,
                dependencies: [7],
            },
            {
                name: 'loongarch(龙芯)',
                checked: false,
                dependencies: [8],
            },
        ],
        dependencies: [],
    },
    {
        id: 'moment',
        name: '朋友圈',
        category: 'feature',
        title: '是否需要支持朋友圈功能？',
        desc: '类似微信朋友圈',
        checked: false,
        dependencies: [1],
    },
    {
        id: 'ptt',
        name: '对讲（非发语音消息）',
        category: 'feature',
        title: '是否需要支持对讲功能？',
        desc: '类似对讲机功能，不是发送语音消息',
        checked: false,
        dependencies: [1, 10],
    },
    {
        id: 'conference',
        name: '高级版音视频',
        category: 'feature',
        title: '是否需要使用高级版音视频功能？',
        desc: '高级版音视频比免费版功能更强大，具体区别请参考：https://docs.wildfirechat.cn/blogs/%E9%87%8E%E7%81%AB%E9%9F%B3%E8%A7%86%E9%A2%91%E7%AE%80%E4%BB%8B.html',
        checked: false,
        dependencies: [1, 9],
    },
    {
        id: 'imserver',
        name: '专业版 IM 服务',
        desc: '专业版 IM 比社区版 IM 更强大，具体区别请参考：https://docs.wildfirechat.cn/commercial_server',
        category: 'feature',
        title: 'IM 服务端是否需要支持集群部署？',
        checked: false,
        dependencies: [1],
    },
]

export const commercial_products = [
    {
        id: 1,
        name: '专业版 IM-Server',
        desc: '专业版 IM 服务',
        price: 29000.00,
    },
    {
        id: 2,
        name: 'Windows + macOS PC SDK',
        desc: 'Windows 和 macOS 端的 PC SDK',
        price: 29000.00,
    },
    {
        id: 3,
        name: 'Web SDK',
        desc: '运行在浏览器的 Web 应用使用的 SDK',
        price: 10000.00,
    },
    {
        id: 4,
        name: '小程序 SDK',
        desc: '运行在浏览器的 Web 应用使用的 SDK',
        price: 10000.00,
    },
    {
        id: 5,
        name: 'Linux PC SDK(x86/amd64)',
        desc: 'CPU 架构为 x86/amd64 的 Linux 端使用的 PC SDK',
        price: 29000.00,
    },
    {
        id: 6,
        name: 'Linux PC SDK(arm64)',
        desc: 'CPU 架构为 arm64 的 Linux 端使用的 PC SDK',
        price: 29000.00,
    },
    {
        id: 7,
        name: 'Linux PC SDK(sw)',
        desc: 'CPU 架构为申威的 Linux 端使用的 PC SDK',
        price: 29000.00,
    },
    {
        id: 8,
        name: 'Linux PC SDK(loongarch)',
        desc: 'CPU 架构为龙芯的 Linux 端使用的 PC SDK',
        price: 29000.00,
    },
    {
        id: 9,
        name: '高级版音视频 SDK',
        desc: '实现音视频通话，及音视频会议功能',
        price: 59000.00,
    },
    {
        id: 10,
        name: '对讲 SDK',
        desc: '实现对讲功能',
        price: 10000.00,
    },
    {
        id: 11,
        name: '鸿蒙next SDK',
        desc: '支持鸿蒙 next',
        price: 10000.00,
    },

]